metadata:
  used:          
    label: Disk Space Used
    units: GB
    precision: 0
  size:
    label: Disk Size
    units: GB
    precision: 0
  capacity:
    label: Disk Capacity
    units: %
    precision: 0
  avail:
    label: Disk Space Available
    units: GB
    precision: 0
    larger_is_better: true

triggers:
  - type: peak
    dname: capacity
    max_value: 85