metadata:
  request_rate:
    precision: 2
    label: Requests
    units: req/min
  average_request_length:
    precision: 2
    units: sec
  slow_request_rate:
    precision: 2
    label: Slow Requests
    units: req/min
  slow_requests_percentage:
    precision: 0
    units: "%"

triggers:
  - type: trend
    dname: request_rate
    direction: UP
    percentage_change: 200
    duration: 60
    window_reference: LAST_WEEK
    min_value: 100
  - type: trend
    dname: average_request_length
    direction: UP
    percentage_change: 200
    duration: 60
    window_reference: LAST_WEEK
    min_value: 0.3 