metadata:
  rps:
    label: Reads/sec
    precision: 0
  wps:
    label: Writes/sec
    precision: 0
  rkbps:
    label: Read kBps
    precision: 1
    units: kB/s
  wkbps:
    label: Write kBps
    precision: 1
    units: kB/s
  await:
    label: I/O Wait
    precision: 1
    units: ms
  util:
    label: Utilization
    precision: 0
    units: %
  aveq:
    label: Average Queue Size
    precision: 1

triggers:
  - type: peak
    dname: util
    max_value: 80%
